name = "Ebuild"
code_fence_block_name = "ebuild"
grammar = "bash"
path_suffixes = ["ebuild"]
line_comments = ["# "]
tab_size = 4
hard_tabs = true

autoclose_before = "}])"
brackets = [
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = true },
    { start = "{", end = "}", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "do", end = "done", close = false, newline = true, not_in = [
        "comment",
        "string",
    ] },
    { start = "then", end = "fi", close = false, newline = true, not_in = [
        "comment",
        "string",
    ] },
    { start = "then", end = "else", close = false, newline = true, not_in = [
        "comment",
        "string",
    ] },
    { start = "then", end = "elif", close = false, newline = true, not_in = [
        "comment",
        "string",
    ] },
    { start = "in", end = "esac", close = false, newline = true, not_in = [
        "comment",
        "string",
    ] },
]

increase_indent_pattern = "(\\s*|;)(do|then|in|else|elif)\\b.*$"
decrease_indent_pattern = "(\\s*|;)\\b(fi|done|esac|else|elif)\\b.*$"
